# Generated by Django 5.1.7 on 2025-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time_control',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical')], default='blitz', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='blitz_elo',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='blitz_rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='user',
            name='blitz_volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AddField(
            model_name='user',
            name='bullet_elo',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='bullet_rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='user',
            name='bullet_volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AddField(
            model_name='user',
            name='classical_elo',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='classical_rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='user',
            name='classical_volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AddField(
            model_name='user',
            name='rapid_elo',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rapid_rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='user',
            name='rapid_volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(blank=True, choices=[('swiss', 'Swiss'), ('round_robin', 'Round Robin'), ('double_round_robin', 'Double Round Robin')], max_length=20, null=True),
        ),
    ]
