# Generated by Django 5.1.7 on 2025-03-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_tournament_time_control_user_blitz_elo_user_blitz_rd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fide_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
