# Generated by Django 5.1.7 on 2025-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_user_fide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstanding',
            name='previous_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
