# Generated by Django 5.1.7 on 2025-03-13 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_tournamentstanding_previous_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
