# Generated by Django 5.1.7 on 2025-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('tournament_win_1', 'Tournament Champion'), ('tournament_win_3', 'Triple Crown'), ('tournament_win_5', 'Dominator'), ('tournament_win_10', 'Dynasty Builder'), ('silver_medal_3', 'Silver Collector'), ('silver_medal_5', 'Silver Hoarder'), ('bronze_medal_3', 'Bronze Collector'), ('bronze_medal_5', 'Bronze Hoarder'), ('hat_trick', 'Hat Trick'), ('winning_streak_5', 'Winning Streak'), ('winning_streak_10', 'Unstoppable'), ('white_dominator', 'White Dominator'), ('black_defender', 'Black Defender'), ('clean_sweep', 'Clean Sweep'), ('perfect_score', 'Perfect Score'), ('undefeated', 'Undefeated'), ('tournament_veteran_10', 'Tournament Veteran'), ('tournament_veteran_25', 'Tournament Master'), ('tournament_veteran_50', 'Tournament Legend'), ('comeback_kid', 'Comeback Kid'), ('underdog', 'Underdog'), ('giant_slayer', 'Giant Slayer'), ('swiss_master', 'Swiss Master'), ('round_robin_champion', 'Round Robin Champion'), ('double_round_robin_king', 'Double Round Robin King'), ('bullet_blitzer', 'Bullet Blitzer'), ('blitz_boss', 'Blitz Boss'), ('rapid_ruler', 'Rapid Ruler'), ('classical_conqueror', 'Classical Conqueror'), ('rating_1600', 'Rising Star'), ('rating_1800', 'Advanced Player'), ('rating_2000', 'Expert Player'), ('rating_2200', 'Master Player'), ('support_bear', 'Emotional Support Bear'), ('dummies', 'Chess for Dummies'), ('goat', 'The Ace'), ('truce_seeker', 'Truce Seeker'), ('social_butterfly', 'Social Butterfly'), ('rival_nemesis', 'Rival Nemesis'), ('kingmaker', 'Kingmaker'), ('bar_legend', 'Bar Legend'), ('century_club', 'Century Club'), ('blitz_marathon', 'Blitz Marathon'), ('phoenix_rising', 'Phoenix Rising'), ('draw_magnet', 'Draw Magnet'), ('the_spoiler', 'The Spoiler'), ('last_stand', 'Last Stand'), ('grand_slam', 'Grand Slam'), ('format_master', 'Format Master'), ('seasonal_champion', 'Seasonal Champion'), ('the_perfectionist', 'The Perfectionist'), ('comeback_king', 'Comeback King/Queen'), ('late_bloomer', 'Late Bloomer'), ('score_maximizer', 'Score Maximizer')], max_length=50),
        ),
    ]
